version: '3'

services:
  db:
    container_name: postgres_web
    image: 'postgres:15'
    hostname: postgre_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    command: "-p 5432"
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null 
    working_dir: /home/app
    container_name: web-app
    volumes: 
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - db





